twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: null
  globals:
    pumukit_info:  "%pumukit.info%"
    locales:       "%pumukit.locales%"
    enable_cookie_banner: '%env(bool:ENABLE_COOKIE_BANNER)%'
    cookie_banner_privacy_link: "%env(COOKIE_BANNER_PRIVACY_LINK)%"
